/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Alumno;
import dmp.SimpleCSVReader;
import dmp.SimpleCSVWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author DanielPM.dev
 */
public class VentanaEntrada extends javax.swing.JFrame {

    private List<Alumno> listaAlumnos = new ArrayList();
    SimpleCSVReader lector = new SimpleCSVReader();
    SimpleCSVWriter escritor = new SimpleCSVWriter();
    private final static String RUTA_IMPORTAR = "./src/archivos/importar.csv";
    private final static String RUTA_EXPORTAR = "./src/archivos/resultado.csv";        

    /**
     * Creates new form VentanaEntrada
     */
    public VentanaEntrada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btListaAlumnos = new javax.swing.JButton();
        btFichaIndividual = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCargarFichero = new javax.swing.JMenuItem();
        jmiGuardarFichero = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btListaAlumnos.setText("Vista Lista de Alumnos");
        btListaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarVistaLista(evt);
            }
        });

        btFichaIndividual.setText("Vista Ficha Individual");
        btFichaIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarVistaIndividual(evt);
            }
        });

        jMenu1.setText("Archivo");

        jmiCargarFichero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiCargarFichero.setMnemonic('C');
        jmiCargarFichero.setText("Cargar fichero CSV");
        jmiCargarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionCargar(evt);
            }
        });
        jMenu1.add(jmiCargarFichero);

        jmiGuardarFichero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmiGuardarFichero.setMnemonic('G');
        jmiGuardarFichero.setText("Guardar fichero CSV");
        jmiGuardarFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionGuardar(evt);
            }
        });
        jMenu1.add(jmiGuardarFichero);
        jMenu1.add(jSeparator1);

        jmiSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmiSalir.setMnemonic('S');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accionSalir(evt);
            }
        });
        jMenu1.add(jmiSalir);

        jMenuBar1.add(jMenu1);

        jMenu3.setMnemonic('A');
        jMenu3.setText("Ayuda");

        jmiAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jmiAcerca.setText("Acerca de...");
        jmiAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarAcercaDe(evt);
            }
        });
        jMenu3.add(jmiAcerca);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btListaAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFichaIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btListaAlumnos)
                .addGap(35, 35, 35)
                .addComponent(btFichaIndividual)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lanzarVistaLista(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarVistaLista
        VentanaLista vistaLista = new VentanaLista(this, true, this.listaAlumnos);
        vistaLista.setVisible(true);
    }//GEN-LAST:event_lanzarVistaLista

    private void lanzarVistaIndividual(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarVistaIndividual
        VentanaIndividual vistaIndividual = new VentanaIndividual(this, true, this.listaAlumnos);
        vistaIndividual.setVisible(true);
    }//GEN-LAST:event_lanzarVistaIndividual

    private void lanzarAcercaDe(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarAcercaDe
        AcercaDe info = new AcercaDe(this, true);
        info.setVisible(true);
    }//GEN-LAST:event_lanzarAcercaDe

    private void accionSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionSalir
        System.exit(0);
    }//GEN-LAST:event_accionSalir

    private void accionCargar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionCargar
        this.listaAlumnos = lector.cargarAlumnosDesdeCSV(RUTA_IMPORTAR);              
                
        if (!listaAlumnos.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Se han cargado " + listaAlumnos.size() + " alumnos correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se han podido cargar los datos. La lista está vacía.");
        }
    }//GEN-LAST:event_accionCargar

    private void accionGuardar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accionGuardar
        boolean exportacionExitosa = escritor.exportarAlumnosACSV(listaAlumnos, RUTA_EXPORTAR);

        // Mostrar mensaje según el resultado de la exportación
        if (exportacionExitosa) {
            JOptionPane.showMessageDialog(null, "Exportación a CSV completada con éxito.");
        } else {
            JOptionPane.showMessageDialog(null, "Error al exportar a CSV.");
        }
    }//GEN-LAST:event_accionGuardar

    public List<Alumno> getListaAlumnos() {
        return listaAlumnos;
    }

    public void setListaAlumnos(List<Alumno> listaAlumnos) {
        this.listaAlumnos = listaAlumnos;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEntrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEntrada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFichaIndividual;
    private javax.swing.JButton btListaAlumnos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmiAcerca;
    private javax.swing.JMenuItem jmiCargarFichero;
    private javax.swing.JMenuItem jmiGuardarFichero;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
}
